contentColumnType: string
fieldGroup: efb42c2a-8e37-402f-abd3-b1576e7871fa
handle: branchIcon
instructions: ''
name: 'branch icon'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:e74d52ab-552e-41ec-940f-cffa450e2f75'
  defaultUploadLocationSubpath: ''
  limit: '5'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add branch icon'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e74d52ab-552e-41ec-940f-cffa450e2f75'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e74d52ab-552e-41ec-940f-cffa450e2f75'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
