enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  e2c5d370-955c-4eb9-9b63-4c5a5f5c8edd:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
